`ifndef DEFINE_STATE

// This defines the states
typedef enum logic [2:0] {
	S_IDLE,
	S_ENABLE_UART_RX,
	S_WAIT_UART_RX,
	S_MILESTONE_2_START,
	S_MILESTONE_1_START
} top_state_type;

typedef enum logic [7:0] {
	S_START,
	S_DELAY,
	S_LEAD_IN_0,
	S_LEAD_IN_1,
	S_LEAD_IN_2,
	S_LEAD_IN_3,
	S_LEAD_IN_4,
	S_LEAD_IN_5,
	S_LEAD_IN_6,
	S_LEAD_IN_7,
	S_COMMON_8,
	S_COMMON_9,
	S_COMMON_10,
	S_COMMON_11,
	S_COMMON_12,
	S_COMMON_13,
	S_COMMON_14,
	S_COMMON_15,
	S_COMMON_16,
	S_COMMON_17,
	S_COMMON_18,
	S_COMMON_19,
	S_LEAD_OUT_1,
	S_LEAD_OUT_2,
	S_LEAD_OUT_3,
	S_MILESTONE_1_DONE
} M1_state_type;

typedef enum logic [7:0] {
	S_M2_IDLE,
	S_FETCH_SPRIME_0,
	S_FETCH_SPRIME_1,
	S_FETCH_SPRIME_2,
	S_FETCH_SPRIME_3,
	S_FETCH_SPRIME_4,
	S_COMPUTE_T_0,
	S_COMPUTE_T_1,
	S_COMPUTE_T_2,
	S_COMPUTE_T_3,
	S_COMPUTE_T_4,
	S_COMPUTE_S_0,
	S_COMPUTE_S_1,
	S_COMPUTE_S_2,
	S_COMPUTE_S_3,
	S_COMPUTE_S_4,
	S_WRITE_S_0,
	S_WRITE_S_1,
	S_WRITE_S_2,
	S_WRITE_S_3,
	S_WRITE_S_4,
	S_WRITE_S_5,
	S_MILESTONE_2_DONE
} M2_state_type;

typedef enum logic [1:0] {
	S_RXC_IDLE,
	S_RXC_SYNC,
	S_RXC_ASSEMBLE_DATA,
	S_RXC_STOP_BIT
} RX_Controller_state_type;

typedef enum logic [2:0] {
	S_US_IDLE,
	S_US_STRIP_FILE_HEADER_1,
	S_US_STRIP_FILE_HEADER_2,
	S_US_START_FIRST_BYTE_RECEIVE,
	S_US_WRITE_FIRST_BYTE,
	S_US_START_SECOND_BYTE_RECEIVE,
	S_US_WRITE_SECOND_BYTE
} UART_SRAM_state_type;

typedef enum logic [3:0] {
	S_VS_WAIT_NEW_PIXEL_ROW,
	S_VS_NEW_PIXEL_ROW_DELAY_1,
	S_VS_NEW_PIXEL_ROW_DELAY_2,
	S_VS_NEW_PIXEL_ROW_DELAY_3,
	S_VS_NEW_PIXEL_ROW_DELAY_4,
	S_VS_NEW_PIXEL_ROW_DELAY_5,
	S_VS_FETCH_PIXEL_DATA_0,
	S_VS_FETCH_PIXEL_DATA_1,
	S_VS_FETCH_PIXEL_DATA_2,
	S_VS_FETCH_PIXEL_DATA_3
} VGA_SRAM_state_type;

`define DEFINE_STATE 1
`endif
